### ДЗ к лекции 2

Тема “Создание признакового пространства”

Продолжим обработку данных с Твиттера. 

1. Создайте мешок слов с помощью sklearn.feature_extraction.text.CountVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
Исключим стоп-слова с помощью stop_words='english'. 
Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью CountVectorizer.get_feature_names().
 
2. Создайте мешок слов с помощью sklearn.feature_extraction.text.TfidfVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
Исключим стоп-слова с помощью stop_words='english'.
Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью TfidfVectorizer.get_feature_names().
3. Создайте мешок слов с помощью sklearn.feature_extraction.text.HashingVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
Ограничим количество фичей, с помощью n_features = 1000.(можно изменить)
Исключим стоп-слова с помощью stop_words='english'.
4. Проверьте ваши векторайзеры на корпусе который использовали на вебинаре, составьте таблицу метод векторизации и скор который вы получили (в методах векторизации по изменяйте параметры что бы добиться лучшего скора) обратите внимание как падает/растёт скор при уменьшении количества фичей, и изменении параметров, так же попробуйте применить к векторайзерам PCA для сокращения размерности посмотрите на качество сделайте выводы


In [7]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import warnings 
warnings.filterwarnings("ignore", category=DeprecationWarning)
import os

from sklearn.feature_extraction.text import CountVectorizer

In [44]:
df = pd.read_pickle("clear_tweets.pkl")

In [5]:
df.columns

Index(['id', 'label', 'tweet', 'tweet_token', 'tweet_token_filtered',
       'tweet_stemmed', 'tweet_lemmatized'],
      dtype='object')

1. Создайте мешок слов с помощью sklearn.feature_extraction.text.CountVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно. Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df. Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000. Исключим стоп-слова с помощью stop_words='english'. Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью CountVectorizer.get_feature_names().

In [63]:
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words("english"))

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/sergeysolovyev/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [66]:
documents = df['tweet_lemmatized'].apply(' '.join,1).values
count_vectorizer = CountVectorizer(ngram_range=(1, 1), analyzer='word', max_df = 0.9, max_features = 1000, stop_words='english', lowercase=False)

# Создаем the Bag-of-Words модель
bag_of_words = count_vectorizer.fit_transform(documents)

# Отобразим Bag-of-Words модель как DataFrame
feature_names = count_vectorizer.get_feature_names()
pd.DataFrame(bag_of_words.toarray(), columns = feature_names)

able  absolutely  account  act  action  actor  actually  adapt  add  \
0         0           0        0    0       0      0         0      0    0   
1         0           0        0    0       0      0         0      0    0   
2         0           0        0    0       0      0         0      0    0   
3         0           0        0    0       0      0         0      0    0   
4         0           0        0    0       0      0         0      0    0   
...     ...         ...      ...  ...     ...    ...       ...    ...  ...   
49154     0           0        0    0       0      0         0      0    0   
49155     0           0        0    0       0      0         0      0    0   
49156     0           0        0    0       0      0         0      0    0   
49157     0           0        0    0       0      0         0      0    0   
49158     0           0        0    0       0      0         0      0    0   

       adult  ...  yes  yesterday  yo  yoga  york  young  youth  youtube  yr  \
0          0  ...    0          0   0     0     0      0      0        0   0   
1          0  ...    0          0   0     0     0      0      0        0   0   
2          0  ...    0          0   0     0     0      0      0        0   0   
3          0  ...    0          0   0     0     0      0      0        0   0   
4          0  ...    0          0   0     0     0      0      0        0   0   
...      ...  ...  ...        ...  ..   ...   ...    ...    ...      ...  ..   
49154      0  ...    0          0   0     0     0      0      0        0   0   
49155      0  ...    0          0   0     0     0      0      0        0   0   
49156      0  ...    0          0   0     0     0      0      0        0   0   
49157      0  ...    0          0   0     0     0      0      0        0   0   
49158      0  ...    0          0   0     0     0      0      0        0   0   

       yummy  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
49154      0  
49155      0  
49156      0  
49157      0  
49158      0  

[49159 rows x 1000 columns]

In [67]:
documents = df['tweet_stemmed'].apply(' '.join,1).values
count_vectorizer = CountVectorizer(ngram_range=(1, 1), analyzer='word', max_df = 0.9, max_features = 1000, stop_words='english', lowercase=False)

# Создаем the Bag-of-Words модель
bag_of_words = count_vectorizer.fit_transform(documents)

# Отобразим Bag-of-Words модель как DataFrame
feature_names = count_vectorizer.get_feature_names()
pd.DataFrame(bag_of_words.toarray(), columns = feature_names)

abl  absolut  accept  account  act  action  actor  actual  ad  adapt  \
0        0        0       0        0    0       0      0       0   0      0   
1        0        0       0        0    0       0      0       0   0      0   
2        0        0       0        0    0       0      0       0   0      0   
3        0        0       0        0    0       0      0       0   0      0   
4        0        0       0        0    0       0      0       0   0      0   
...    ...      ...     ...      ...  ...     ...    ...     ...  ..    ...   
49154    0        0       0        0    0       0      0       0   0      0   
49155    0        0       0        0    0       0      0       0   0      0   
49156    0        0       0        0    0       0      0       0   0      0   
49157    0        0       0        0    0       0      0       0   0      0   
49158    0        0       0        0    0       0      0       0   0      0   

       ...  yeah  year  yesterday  yo  yoga  york  young  youtub  yr  yummi  
0      ...     0     0          0   0     0     0      0       0   0      0  
1      ...     0     0          0   0     0     0      0       0   0      0  
2      ...     0     0          0   0     0     0      0       0   0      0  
3      ...     0     0          0   0     0     0      0       0   0      0  
4      ...     0     0          0   0     0     0      0       0   0      0  
...    ...   ...   ...        ...  ..   ...   ...    ...     ...  ..    ...  
49154  ...     0     0          0   0     0     0      0       0   0      0  
49155  ...     0     0          0   0     0     0      0       0   0      0  
49156  ...     0     0          0   0     0     0      0       0   0      0  
49157  ...     0     0          0   0     0     0      0       0   0      0  
49158  ...     0     0          0   0     0     0      0       0   0      0  

[49159 rows x 1000 columns]

2. Создайте мешок слов с помощью sklearn.feature_extraction.text.TfidfVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно. Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df. Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000. Исключим стоп-слова с помощью stop_words='english'. Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью TfidfVectorizer.get_feature_names().

In [71]:
from sklearn.feature_extraction.text import TfidfVectorizer

document = df['tweet_stemmed'].apply(' '.join,1).values
tfidf_vectorizer = TfidfVectorizer(max_df=0.9,max_features=1000,stop_words='english')
values = tfidf_vectorizer.fit_transform(document)

# Show the Model as a pandas DataFrame
feature_names = tfidf_vectorizer.get_feature_names()
pd.DataFrame(values.toarray(), columns = feature_names)

abl  absolut  accept  account  act  action  actor  actual   ad  adapt  \
0      0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
1      0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
2      0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
3      0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
4      0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
...    ...      ...     ...      ...  ...     ...    ...     ...  ...    ...   
49154  0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
49155  0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
49156  0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
49157  0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
49158  0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   

       ...  yeah  year  yesterday   yo  yoga  york  young  youtub   yr  yummi  
0      ...   0.0   0.0        0.0  0.0   0.0   0.0    0.0     0.0  0.0    0.0  
1      ...   0.0   0.0        0.0  0.0   0.0   0.0    0.0     0.0  0.0    0.0  
2      ...   0.0   0.0        0.0  0.0   0.0   0.0    0.0     0.0  0.0    0.0  
3      ...   0.0   0.0        0.0  0.0   0.0   0.0    0.0     0.0  0.0    0.0  
4      ...   0.0   0.0        0.0  0.0   0.0   0.0    0.0     0.0  0.0    0.0  
...    ...   ...   ...        ...  ...   ...   ...    ...     ...  ...    ...  
49154  ...   0.0   0.0        0.0  0.0   0.0   0.0    0.0     0.0  0.0    0.0  
49155  ...   0.0   0.0        0.0  0.0   0.0   0.0    0.0     0.0  0.0    0.0  
49156  ...   0.0   0.0        0.0  0.0   0.0   0.0    0.0     0.0  0.0    0.0  
49157  ...   0.0   0.0        0.0  0.0   0.0   0.0    0.0     0.0  0.0    0.0  
49158  ...   0.0   0.0        0.0  0.0   0.0   0.0    0.0     0.0  0.0    0.0  

[49159 rows x 1000 columns]

In [72]:
from sklearn.feature_extraction.text import TfidfVectorizer

document = df['tweet_lemmatized'].apply(' '.join,1).values
tfidf_vectorizer = TfidfVectorizer(max_df=0.9,max_features=1000,stop_words='english')
values = tfidf_vectorizer.fit_transform(document)

# Show the Model as a pandas DataFrame
feature_names = tfidf_vectorizer.get_feature_names()
pd.DataFrame(values.toarray(), columns = feature_names)

able  absolutely  account  act  action  actor  actually  adapt  add  \
0       0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
1       0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
2       0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
3       0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
4       0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
...     ...         ...      ...  ...     ...    ...       ...    ...  ...   
49154   0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
49155   0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
49156   0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
49157   0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
49158   0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   

       adult  ...  yes  yesterday   yo  yoga  york  young  youth  youtube  \
0        0.0  ...  0.0        0.0  0.0   0.0   0.0    0.0    0.0      0.0   
1        0.0  ...  0.0        0.0  0.0   0.0   0.0    0.0    0.0      0.0   
2        0.0  ...  0.0        0.0  0.0   0.0   0.0    0.0    0.0      0.0   
3        0.0  ...  0.0        0.0  0.0   0.0   0.0    0.0    0.0      0.0   
4        0.0  ...  0.0        0.0  0.0   0.0   0.0    0.0    0.0      0.0   
...      ...  ...  ...        ...  ...   ...   ...    ...    ...      ...   
49154    0.0  ...  0.0        0.0  0.0   0.0   0.0    0.0    0.0      0.0   
49155    0.0  ...  0.0        0.0  0.0   0.0   0.0    0.0    0.0      0.0   
49156    0.0  ...  0.0        0.0  0.0   0.0   0.0    0.0    0.0      0.0   
49157    0.0  ...  0.0        0.0  0.0   0.0   0.0    0.0    0.0      0.0   
49158    0.0  ...  0.0        0.0  0.0   0.0   0.0    0.0    0.0      0.0   

        yr  yummy  
0      0.0    0.0  
1      0.0    0.0  
2      0.0    0.0  
3      0.0    0.0  
4      0.0    0.0  
...    ...    ...  
49154  0.0    0.0  
49155  0.0    0.0  
49156  0.0    0.0  
49157  0.0    0.0  
49158  0.0    0.0  

[49159 rows x 1000 columns]

3. Создайте мешок слов с помощью sklearn.feature_extraction.text.HashingVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно. Ограничим количество фичей, с помощью n_features = 1000.(можно изменить) Исключим стоп-слова с помощью stop_words='english'.

In [76]:
from sklearn.feature_extraction.text import HashingVectorizer

document = df['tweet_lemmatized'].apply(' '.join,1).values
vectorizer = HashingVectorizer(n_features=1000, stop_words='english')
values = vectorizer.fit_transform(document)
print(values.shape)
print(values.toarray())

(49159, 1000)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [77]:
from sklearn.feature_extraction.text import HashingVectorizer

document = df['tweet_stemmed'].apply(' '.join,1).values
vectorizer = HashingVectorizer(n_features=1000, stop_words='english')
values = vectorizer.fit_transform(document)
print(values.shape)
print(values.toarray())

(49159, 1000)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


4.Проверьте ваши векторайзеры на корпусе который использовали на вебинаре, составьте таблицу метод векторизации и скор который вы получили (в методах векторизации по изменяйте параметры что бы добиться лучшего скора) обратите внимание как падает/растёт скор при уменьшении количества фичей, и изменении параметров, так же попробуйте применить к векторайзерам PCA для сокращения размерности посмотрите на качество сделайте выводы

In [78]:
# Загружаем данные
data = open('corpus').read()
labels, texts = [], []
for i, line in enumerate(data.split("\n")):
    content = line.split()
    labels.append(content[0])
    texts.append(" ".join(content[1:]))

# создаем df
trainDF = pd.DataFrame()
trainDF['text'] = texts
trainDF['label'] = labels
trainDF.head(5)

text       label
0  Stuning even for the non-gamer: This sound tra...  __label__2
1  The best soundtrack ever to anything.: I'm rea...  __label__2
2  Amazing!: This soundtrack is my favorite music...  __label__2
3  Excellent Soundtrack: I truly like this soundt...  __label__2
4  Remember, Pull Your Jaw Off The Floor After He...  __label__2

In [81]:
from sklearn import model_selection, preprocessing, linear_model
from sklearn.metrics import accuracy_score
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(trainDF['text'], trainDF['label'])

# labelEncode целевую переменную
encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)
valid_y = encoder.fit_transform(valid_y)


count_vect = CountVectorizer(analyzer='word', token_pattern=r'\w{1,}')
count_vect.fit(trainDF['text'])

xtrain_count =  count_vect.transform(train_x)
xvalid_count =  count_vect.transform(valid_x)

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_count, train_y)
predictions = classifier.predict(xvalid_count)
predictions

/usr/local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 1, 1, ..., 0, 1, 1])

In [95]:
def investigation_scor_vectorasers(max_features = 1000, max_df=0.9):
    count_vectorizer = CountVectorizer(ngram_range=(1, 1), analyzer='word', max_df = max_df, max_features = max_features, stop_words='english', lowercase=False)
    tfidf_vectorizer = TfidfVectorizer(max_df=max_df,max_features=max_features,stop_words='english')
    hashing_vectorizer = HashingVectorizer(n_features=max_features, stop_words='english')

    vectorizers = [count_vectorizer, tfidf_vectorizer, hashing_vectorizer]
    scor_vs_vectorasers = []

    for v in vectorizers:
        v.fit(trainDF['text'])
        xtrain_count =  v.transform(train_x)
        xvalid_count =  v.transform(valid_x)

        classifier = linear_model.LogisticRegression()
        classifier.fit(xtrain_count, train_y)
        predictions = classifier.predict(xvalid_count)
        scor_vs_vectorasers.append([v, accuracy_score(valid_y, predictions)])
    return pd.DataFrame(scor_vs_vectorasers, columns = ['Vectoraser', 'Score'])

In [96]:
investigation_scor_vectorasers(max_features = 1000, max_df=0.9)

Vectoraser   Score
0  CountVectorizer(lowercase=False, max_df=0.9, m...  0.8120
1  TfidfVectorizer(max_df=0.9, max_features=1000,...  0.8316
2  HashingVectorizer(n_features=1000, stop_words=...  0.7796

In [97]:
investigation_scor_vectorasers(max_features = 5000, max_df=0.9)

/usr/local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Vectoraser   Score
0  CountVectorizer(lowercase=False, max_df=0.9, m...  0.8316
1  TfidfVectorizer(max_df=0.9, max_features=5000,...  0.8464
2  HashingVectorizer(n_features=5000, stop_words=...  0.8216

In [98]:
investigation_scor_vectorasers(max_features = 1000, max_df=0.6)

Vectoraser   Score
0  CountVectorizer(lowercase=False, max_df=0.6, m...  0.8120
1  TfidfVectorizer(max_df=0.6, max_features=1000,...  0.8316
2  HashingVectorizer(n_features=1000, stop_words=...  0.7796

In [99]:
investigation_scor_vectorasers(max_features = 1000, max_df=1)

Vectoraser   Score
0  CountVectorizer(lowercase=False, max_df=1, max...  0.5016
1  TfidfVectorizer(max_df=1, max_features=1000, s...  0.5016
2  HashingVectorizer(n_features=1000, stop_words=...  0.7796

### Вывод: с увеличением количество фичей, скор растет, но на max_df что то никак не меняется